<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\TreeToAssign\BuildInterface\TreeToAssignInterface;

/**
 * CategoryHasProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryHasProductRepository extends EntityRepository implements TreeToAssignInterface
{

    public function findBoxleftHasBoxright($boxLeftId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT hasEntity, category
            FROM AppBundle:CategoryHasProduct hasEntity
            INNER JOIN hasEntity.category category
            INNER JOIN hasEntity.product product
            WHERE
            category.idIncrement = :id AND
            product.isActive = :active 
            ORDER BY product.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $boxLeftId);

        return $query->getResult();
    }

    public function findBoxRightIdsByBoxLeftValue($boxLeftId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT product.idIncrement
            FROM AppBundle:CategoryHasProduct hasEntity
            INNER JOIN hasEntity.category category
            INNER JOIN hasEntity.product product
            WHERE
            hasEntity.category = :boxLeftId AND
            category.isActive = :active AND
            product.isActive = :active 
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('boxLeftId', $boxLeftId);

        $query = $query->getScalarResult();

        $ids = [];
        foreach ($query as $key => $value){
            $ids[] = isset($value['idIncrement']) ? $value['idIncrement'] : null;
        }

        return $ids;
    }

    public function findAssociatedEntity($boxLeftId, $boxRightId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT hasEntity
            FROM AppBundle:CategoryHasProduct hasEntity
            INNER JOIN hasEntity.category category
            INNER JOIN hasEntity.product product
            WHERE
            category.idIncrement = :boxLeftId AND
            product.idIncrement = :boxRightId AND
            category.isActive = :active AND
            product.isActive = :active 
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('boxLeftId', $boxLeftId);
        $query->setParameter('boxRightId', $boxRightId);

        return $query->getOneOrNullResult();
    }

    public function findProductsByCategory($categoryId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT catHasProd, category
            FROM AppBundle:CategoryHasProduct catHasProd
            INNER JOIN catHasProd.category category
            WHERE
            category.idIncrement = :categoryId
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('categoryId', $categoryId);

        return $query->getResult();
    }


    /*
    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT catHasProd
            FROM AppBundle:CategoryHasProduct catHasProd
            WHERE
            catHasProd.idIncrement = :id
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    */





}
