<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository implements CrudInterface
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC'], $limit, $offset);
    }

    public function findAllByParent($parent)
    {
        // TODO: Implement findAllByParent() method.
    }

    public function findOneById($id)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT product
            FROM AppBundle:Product product
            WHERE
            product.idIncrement = :id AND
            product.isActive = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    public function search($q)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT product
            FROM AppBundle:Product product
            WHERE
            product.name LIKE :q AND
            product.isActive = :active
            ORDER BY product.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('q', '%' . $q . '%');

        return $query->getResult();
    }

}
